### ISSUE TITLE
Implement the Meshes class

### ISSUE THREAD

**Issue by davidliii** [PurdueDualityLab/tf-models#6]
## Task Description
Implement the Mesh class, as described in https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/structures/meshes.html
Write your code and tests in this folder: https://github.com/PurdueDualityLab/tf-models/tree/mesh_rcnn/official/vision/beta/projects/mesh_rcnn/ops
🚨 Please follow the [Google Style Guide](https://google.github.io/styleguide/pyguide.html) 🚨 
## Before opening a pull request:
- [ ] Differentially tested against original implementation ✅ 
- [ ] All test cases are written and passed 👍 
- [ ] Code is linted ✏️
