### ISSUE TITLE
TFRecord Generator Pix3D

### ISSUE THREAD

**Issue by jacob-zietek** [PurdueDualityLab/tf-models#7]
## Task Description
Create a TFRecord generator for the Pix3D dataset in https://github.com/PurdueDualityLab/tf-models/tree/mesh_rcnn/official/vision/beta/projects/mesh_rcnn/data.

:rotating_light: Please follow the [Google Style Guide](https://google.github.io/styleguide/pyguide.html) :rotating_light:
## Before opening a pull request:
- [ ] Differentially tested against original implementation :white_check_mark:
- [ ] All test cases are written and passed :+1:
- [ ] Code is linted :pencil2:
