### ISSUE TITLE
Implement Cubify Op

### ISSUE THREAD

**Issue by lenliu3** [PurdueDualityLab/tf-models#9]
## Task Description
Implement the cubify operation, as described in:
https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/ops/cubify.html

Write your code and tests in this folder: https://github.com/PurdueDualityLab/tf-models/tree/mesh_rcnn/official/vision/beta/projects/mesh_rcnn/ops

:rotating_light: Please follow the [Google Style Guide](https://google.github.io/styleguide/pyguide.html) :rotating_light:

## Before opening a pull request:
- [ ] Differentially tested against original implementation :white_check_mark:
- [ ] All test cases are written and passed :+1:
- [ ] Code is linted :pencil2:
